name: german
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cropped_image (1) (1) (2).png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/animals/
    - assets/images/colors/
    - assets/images/numbers/
    - assets/images/family_members/
    - assets/images/FoodAndDrink/
    - assets/images/Clothes_Fasion/
    - assets/images/
    - assets/images/Home_Images/
    - assets/Sounds/Numbers/
    - assets/Sounds/
    - assets/Sounds/Colors/
    - assets/Sounds/Animals/
    - assets/Sounds/Food_Drinks/
    - assets/Sounds/Clothes_Fasion/
    - assets/Sounds/FamilyMembers/
